environment: "dev"

http:
  host: "0.0.0.0"
  port: 8080

log:
  format: "console"
  file_name: "logs/dev.log"
  max_size: 1024
  max_backups: 30
  max_age: 6
  compress: true
  level: "Debug"

jwt:
  key: "00000000000000000000000000000000"

repo:
  rdb:
    addr: "localhost:6379"
    password: "123456"
    db: 0