environment: "dev"

http:
  host: "0.0.0.0"
  port: 8080

log:
  format: "console"
  file_name: "logs/dev.log"
  max_size: 1024
  max_backups: 30
  max_age: 6
  compress: true
  level: "Debug"

jwt:
  key: "s9K7yX6tQ2vU8wD4fG1hJ3lZ5xR0pNcVbM"

repo:
  db:
    dsn: "root:123456@tcp(127.0.0.1:3306)/vega_db?charset=utf8mb4&parseTime=True&loc=Local"
  rdb:
    addr: "127.0.0.1:6379"
    password: "123456"
    db: 0