// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"vega-server/internal/handler"
	"vega-server/internal/repository"
	"vega-server/internal/server"
	"vega-server/internal/service"
	"vega-server/pkg/app"
	"vega-server/pkg/config"
	"vega-server/pkg/jwt"
	"vega-server/pkg/log"
	"vega-server/pkg/server/http"
)

// Injectors from wire.go:

func InitializeApp(conf *config.Config) (*app.App, error) {
	logger := log.NewLogger(conf)
	jwtService := jwt.NewJWTService(conf)
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewDB(conf)
	client := repository.NewRedis(conf)
	repositoryRepository := repository.NewRepository(db, client, logger)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository, jwtService)
	reviewRepository := repository.NewReviewRepository(repositoryRepository)
	reviewService := service.NewReviewService(serviceService, reviewRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService, reviewService)
	movieRepository := repository.NewMovieRepository(repositoryRepository)
	movieService := service.NewMovieService(serviceService, movieRepository)
	movieHandler := handler.NewMovieHandler(handlerHandler, movieService)
	reviewHandler := handler.NewReviewHandler(handlerHandler, reviewService)
	httpServer := server.NewHTTPServer(conf, logger, jwtService, userHandler, movieHandler, reviewHandler)
	appApp := NewApp(httpServer, logger)
	return appApp, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewRepository, repository.NewDB, repository.NewRedis, repository.NewUserRepository, repository.NewMovieRepository, repository.NewReviewRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewMovieService, service.NewReviewService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewMovieHandler, handler.NewReviewHandler)

var ServerSet = wire.NewSet(server.NewHTTPServer)

func NewApp(httpServer *http.Server, logger *log.Logger) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithLogger(logger))
}
